# Data Exploration & Wrangling:

In [ ]:
import pandas as pd
df=pd.read_csv('/content/penguins_lter.csv')
print(df)

    studyName  Sample Number                              Species  Region  \
0     PAL0708              1  Adelie Penguin (Pygoscelis adeliae)  Anvers
1     PAL0708              2  Adelie Penguin (Pygoscelis adeliae)  Anvers
2     PAL0708              3  Adelie Penguin (Pygoscelis adeliae)  Anvers
3     PAL0708              4  Adelie Penguin (Pygoscelis adeliae)  Anvers
4     PAL0708              5  Adelie Penguin (Pygoscelis adeliae)  Anvers
..        ...            ...                                  ...     ...
339   PAL0910            120    Gentoo penguin (Pygoscelis papua)  Anvers
340   PAL0910            121    Gentoo penguin (Pygoscelis papua)  Anvers
341   PAL0910            122    Gentoo penguin (Pygoscelis papua)  Anvers
342   PAL0910            123    Gentoo penguin (Pygoscelis papua)  Anvers
343   PAL0910            124    Gentoo penguin (Pygoscelis papua)  Anvers

        Island               Stage Individual ID Clutch Completion  Date Egg  \
0    Torgersen  Adult, 1 Egg Stage          N1A1               Yes  11/11/07
1    Torgersen  Adult, 1 Egg Stage          N1A2               Yes  11/11/07
2    Torgersen  Adult, 1 Egg Stage          N2A1               Yes  11/16/07
3    Torgersen  Adult, 1 Egg Stage          N2A2               Yes  11/16/07
4    Torgersen  Adult, 1 Egg Stage          N3A1               Yes  11/16/07
..         ...                 ...           ...               ...       ...
339     Biscoe  Adult, 1 Egg Stage         N38A2                No   12/1/09
340     Biscoe  Adult, 1 Egg Stage         N39A1               Yes  11/22/09
341     Biscoe  Adult, 1 Egg Stage         N39A2               Yes  11/22/09
342     Biscoe  Adult, 1 Egg Stage         N43A1               Yes  11/22/09
343     Biscoe  Adult, 1 Egg Stage         N43A2               Yes  11/22/09

     Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  \
0                  39.1               18.7                181.0
1                  39.5               17.4                186.0
2                  40.3               18.0                195.0
3                   NaN                NaN                  NaN
4                  36.7               19.3                193.0
..                  ...                ...                  ...
339                 NaN                NaN                  NaN
340                46.8               14.3                215.0
341                50.4               15.7                222.0
342                45.2               14.8                212.0
343                49.9               16.1                213.0

     Body Mass (g)     Sex  Delta 15 N (o/oo)  Delta 13 C (o/oo)  \
0           3750.0    MALE                NaN                NaN
1           3800.0  FEMALE            8.94956          -24.69454
2           3250.0  FEMALE            8.36821          -25.33302
3              NaN     NaN                NaN                NaN
4           3450.0  FEMALE            8.76651          -25.32426
..             ...     ...                ...                ...
339            NaN     NaN                NaN                NaN
340         4850.0  FEMALE            8.41151          -26.13832
341         5750.0    MALE            8.30166          -26.04117
342         5200.0  FEMALE            8.24246          -26.11969
343         5400.0    MALE            8.36390          -26.15531

                           Comments
0    Not enough blood for isotopes.
1                               NaN
2                               NaN
3                Adult not sampled.
4                               NaN
..                              ...
339                             NaN
340                             NaN
341                             NaN
342                             NaN
343                             NaN

[344 rows x 17 columns]

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   studyName            344 non-null    object
 1   Sample Number        344 non-null    int64
 2   Species              344 non-null    object
 3   Region               344 non-null    object
 4   Island               344 non-null    object
 5   Stage                344 non-null    object
 6   Individual ID        344 non-null    object
 7   Clutch Completion    344 non-null    object
 8   Date Egg             344 non-null    object
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  334 non-null    object
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    float64
 16  Comments             26 non-null     object
dtypes: float64(6), int64(1), object(10)
memory usage: 45.8+ KB
None

In [ ]:
print(df.columns)

Index(['studyName', 'Sample Number', 'Species', 'Region', 'Island', 'Stage',
       'Individual ID', 'Clutch Completion', 'Date Egg', 'Culmen Length (mm)',
       'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)', 'Sex',
       'Delta 15 N (o/oo)', 'Delta 13 C (o/oo)', 'Comments'],
      dtype='object')

In [ ]:
print(df.head())

  studyName  Sample Number                              Species  Region  \
0   PAL0708              1  Adelie Penguin (Pygoscelis adeliae)  Anvers
1   PAL0708              2  Adelie Penguin (Pygoscelis adeliae)  Anvers
2   PAL0708              3  Adelie Penguin (Pygoscelis adeliae)  Anvers
3   PAL0708              4  Adelie Penguin (Pygoscelis adeliae)  Anvers
4   PAL0708              5  Adelie Penguin (Pygoscelis adeliae)  Anvers

      Island               Stage Individual ID Clutch Completion  Date Egg  \
0  Torgersen  Adult, 1 Egg Stage          N1A1               Yes  11/11/07
1  Torgersen  Adult, 1 Egg Stage          N1A2               Yes  11/11/07
2  Torgersen  Adult, 1 Egg Stage          N2A1               Yes  11/16/07
3  Torgersen  Adult, 1 Egg Stage          N2A2               Yes  11/16/07
4  Torgersen  Adult, 1 Egg Stage          N3A1               Yes  11/16/07

   Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  Body Mass (g)  \
0                39.1               18.7                181.0         3750.0
1                39.5               17.4                186.0         3800.0
2                40.3               18.0                195.0         3250.0
3                 NaN                NaN                  NaN            NaN
4                36.7               19.3                193.0         3450.0

      Sex  Delta 15 N (o/oo)  Delta 13 C (o/oo)  \
0    MALE                NaN                NaN
1  FEMALE            8.94956          -24.69454
2  FEMALE            8.36821          -25.33302
3     NaN                NaN                NaN
4  FEMALE            8.76651          -25.32426

                         Comments
0  Not enough blood for isotopes.
1                             NaN
2                             NaN
3              Adult not sampled.
4                             NaN

In [ ]:
print(df.tail())

    studyName  Sample Number                            Species  Region  \
339   PAL0910            120  Gentoo penguin (Pygoscelis papua)  Anvers
340   PAL0910            121  Gentoo penguin (Pygoscelis papua)  Anvers
341   PAL0910            122  Gentoo penguin (Pygoscelis papua)  Anvers
342   PAL0910            123  Gentoo penguin (Pygoscelis papua)  Anvers
343   PAL0910            124  Gentoo penguin (Pygoscelis papua)  Anvers

     Island               Stage Individual ID Clutch Completion  Date Egg  \
339  Biscoe  Adult, 1 Egg Stage         N38A2                No   12/1/09
340  Biscoe  Adult, 1 Egg Stage         N39A1               Yes  11/22/09
341  Biscoe  Adult, 1 Egg Stage         N39A2               Yes  11/22/09
342  Biscoe  Adult, 1 Egg Stage         N43A1               Yes  11/22/09
343  Biscoe  Adult, 1 Egg Stage         N43A2               Yes  11/22/09

     Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  \
339                 NaN                NaN                  NaN
340                46.8               14.3                215.0
341                50.4               15.7                222.0
342                45.2               14.8                212.0
343                49.9               16.1                213.0

     Body Mass (g)     Sex  Delta 15 N (o/oo)  Delta 13 C (o/oo) Comments
339            NaN     NaN                NaN                NaN      NaN
340         4850.0  FEMALE            8.41151          -26.13832      NaN
341         5750.0    MALE            8.30166          -26.04117      NaN
342         5200.0  FEMALE            8.24246          -26.11969      NaN
343         5400.0    MALE            8.36390          -26.15531      NaN

In [ ]:
print(df.describe())

       Sample Number  Culmen Length (mm)  Culmen Depth (mm)  \
count     344.000000          342.000000         342.000000
mean       63.151163           43.921930          17.151170
std        40.430199            5.459584           1.974793
min         1.000000           32.100000          13.100000
25%        29.000000           39.225000          15.600000
50%        58.000000           44.450000          17.300000
75%        95.250000           48.500000          18.700000
max       152.000000           59.600000          21.500000

       Flipper Length (mm)  Body Mass (g)  Delta 15 N (o/oo)  \
count           342.000000     342.000000         330.000000
mean            200.915205    4201.754386           8.733382
std              14.061714     801.954536           0.551770
min             172.000000    2700.000000           7.632200
25%             190.000000    3550.000000           8.299890
50%             197.000000    4050.000000           8.652405
75%             213.000000    4750.000000           9.172123
max             231.000000    6300.000000          10.025440

       Delta 13 C (o/oo)
count         331.000000
mean          -25.686292
std             0.793961
min           -27.018540
25%           -26.320305
50%           -25.833520
75%           -25.062050
max           -23.787670

In [ ]:
print(df.isnull().sum())

studyName                0
Sample Number            0
Species                  0
Region                   0
Island                   0
Stage                    0
Individual ID            0
Clutch Completion        0
Date Egg                 0
Culmen Length (mm)       2
Culmen Depth (mm)        2
Flipper Length (mm)      2
Body Mass (g)            2
Sex                     10
Delta 15 N (o/oo)       14
Delta 13 C (o/oo)       13
Comments               318
dtype: int64

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
print(df['Culmen Length (mm)'].value_counts())

Culmen Length (mm)
41.1    7
45.2    6
39.6    5
37.8    5
46.5    5
       ..
41.7    1
53.4    1
55.1    1
48.8    1
49.9    1
Name: count, Length: 164, dtype: int64

In [ ]:
df.dropna(subset=['Comments'], inplace=True)

In [ ]:
print(df.isnull().sum())

studyName               0
Sample Number           0
Species                 0
Region                  0
Island                  0
Stage                   0
Individual ID           0
Clutch Completion       0
Date Egg                0
Culmen Length (mm)      1
Culmen Depth (mm)       1
Flipper Length (mm)     1
Body Mass (g)           1
Sex                     6
Delta 15 N (o/oo)      11
Delta 13 C (o/oo)      11
Comments                0
dtype: int64

In [ ]:
df['Culmen Length (mm)']=df['Culmen Length (mm)'].fillna(df['Culmen Length (mm)'].mode()[0])

In [ ]:
df['Culmen Depth (mm)']=df['Culmen Depth (mm)'].fillna(df['Culmen Depth (mm)'].mean())

In [ ]:
df['Flipper Length (mm)']=df['Flipper Length (mm)'].fillna(df['Flipper Length (mm)'].median())

In [ ]:
df['Body Mass (g)'] = df['Body Mass (g)'].fillna(df['Body Mass (g)'].mode()[0])

In [ ]:
df['Sex']=df['Sex'].fillna(df['Sex'].mode()[0])

In [ ]:
df['Delta 13 C (o/oo)']=df['Delta 13 C (o/oo)'].fillna(df['Delta 13 C (o/oo)'].mode()[0])

In [ ]:
df['Delta 15 N (o/oo)']=df['Delta 15 N (o/oo)'].fillna(df['Delta 15 N (o/oo)'].mode()[0])

In [ ]:
print(df.isnull().sum())

studyName              0
Sample Number          0
Species                0
Region                 0
Island                 0
Stage                  0
Individual ID          0
Clutch Completion      0
Date Egg               0
Culmen Length (mm)     0
Culmen Depth (mm)      0
Flipper Length (mm)    0
Body Mass (g)          0
Sex                    0
Delta 15 N (o/oo)      0
Delta 13 C (o/oo)      0
Comments               0
dtype: int64

##Merge:

In [49]:
cust_data=(pd.read_excel('/content/cust_id.xlsx'))
print(df)

   sales_id  cust_id     city    product   amt
0       101        2  madurai     laptop  4000
1       102        1  chennai      phone  1000
2       103        3      CBE  headphone   200
3       104        1  chennai   keyboard   500

In [50]:
sales_data=(pd.read_excel('/content/sales_data.xlsx'))
print(df)

   sales_id  cust_id     city    product   amt
0       101        2  madurai     laptop  4000
1       102        1  chennai      phone  1000
2       103        3      CBE  headphone   200
3       104        1  chennai   keyboard   500

In [52]:
merge_data=pd.merge(cust_data, sales_data, left_on='Cust_Id', right_on='cust_id')
print(merge_data)

   Cust_Id    Name             Email     City  sales_id  cust_id     city  \
0        1   surya   surya@gmail.com  chennai       102        1  chennai
1        1   surya   surya@gmail.com  chennai       104        1  chennai
2        2  Anjali  anjali@gmail.com  madurai       101        2  madurai
3        3    Ravi    ravi@gmail.com      CBE       103        3      CBE

     product   amt
0      phone  1000
1   keyboard   500
2     laptop  4000
3  headphone   200

In [54]:
right_merge=cust_data.merge(sales_data, how='right', left_on='Cust_Id', right_on='cust_id')
print(right_merge)

   Cust_Id    Name             Email     City  sales_id  cust_id     city  \
0        2  Anjali  anjali@gmail.com  madurai       101        2  madurai
1        1   surya   surya@gmail.com  chennai       102        1  chennai
2        3    Ravi    ravi@gmail.com      CBE       103        3      CBE
3        1   surya   surya@gmail.com  chennai       104        1  chennai

     product   amt
0     laptop  4000
1      phone  1000
2  headphone   200
3   keyboard   500

##JOINS:

In [58]:
emp_df=pd.read_excel('/content/emp_df.xlsx')
print(emp_df)

   emp_id    name position
0     101     anu  manager
1     102     ram    sales
2     103    ravi       HR
3     104  geetha   teller

In [56]:
pro_df=pd.read_excel('/content/pro_data.xlsx')
print(pro_df)

  project_name  budget
0            A   40000
1            B   70000
2            C   50000

In [60]:
join_data=emp_df.join(pro_df)
print(join_data)

   emp_id    name position project_name   budget
0     101     anu  manager            A  40000.0
1     102     ram    sales            B  70000.0
2     103    ravi       HR            C  50000.0
3     104  geetha   teller          NaN      NaN

In [62]:
emp_df.set_index('emp_id', inplace=True)
print(emp_df)

          name position
emp_id
101        anu  manager
102        ram    sales
103       ravi       HR
104     geetha   teller

##Concate:

In [64]:
pd.concat([emp_df,pro_df])

       name position project_name   budget
101     anu  manager          NaN      NaN
102     ram    sales          NaN      NaN
103    ravi       HR          NaN      NaN
104  geetha   teller          NaN      NaN
0       NaN      NaN            A  40000.0
1       NaN      NaN            B  70000.0
2       NaN      NaN            C  50000.0

##Group by:

In [70]:
sales_data.groupby('city')['amt'].mean()

city
CBE         200.0
chennai     750.0
madurai    4000.0
Name: amt, dtype: float64

###Aggregate:

In [71]:
sales_data.groupby('city').agg({'amt':['mean','max','min']})

            amt
           mean   max   min
city
CBE       200.0   200   200
chennai   750.0  1000   500
madurai  4000.0  4000  4000